### ISSUE TITLE
Test failiing for this model

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos9ivc#3]
See logs https://github.com/ersilia-os/eos9ivc/actions/runs/8191634306/job/22401280644

**Comment by DhanshreeA** [comment]
@GemmaTuron assigning this issue to you

**Comment by GemmaTuron** [comment]
I'm on it.
Quick comment @DhanshreeA , on the prints in the Actions there is this block copied many times:
```
    {
        "Identifier": "",
        "BENTO_SERVICE": "",
        "AGE": "",
        "APIS": "",
        "ARTIFACTS": ")"
    },
```

I guess it is a debugging print one of us forgot to delete, but I can't find it and makes it annoying to read through the error log, can you pinpoint it?

**Comment by GemmaTuron** [comment]
the model is solved, should I close this issue @DhanshreeA ?
